<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Inicio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-house',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2024-10-18 14:28:27',
                'updated_at' => '2024-10-18 16:31:13',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2024-10-18 14:28:27',
                'updated_at' => '2024-10-18 16:40:50',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Usuarios',
                'url' => '/admin/users',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 1,
                'created_at' => '2024-10-18 14:28:27',
                'updated_at' => '2025-12-15 13:17:25',
                'route' => NULL,
                'parameters' => '',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 2,
                'created_at' => '2024-10-18 14:28:27',
                'updated_at' => '2024-10-18 16:33:29',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2024-10-18 14:28:27',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2024-10-18 14:28:27',
                'updated_at' => '2024-10-18 16:33:17',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2024-10-18 14:28:27',
                'updated_at' => '2024-10-18 16:40:50',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2024-10-18 14:28:27',
                'updated_at' => '2024-10-18 16:40:50',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2024-10-18 14:28:27',
                'updated_at' => '2024-10-18 16:40:50',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Configuración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2024-10-18 14:28:27',
                'updated_at' => '2025-12-15 13:17:04',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2024-10-18 14:28:45',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2024-10-18 14:28:45',
                'updated_at' => '2024-10-18 16:40:42',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2024-10-18 14:28:46',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Seguridad',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2024-10-18 16:33:05',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Limpiar cache',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-broom',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2024-12-09 12:33:25',
                'updated_at' => '2025-12-15 13:17:04',
                'route' => 'clear.cache',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Administración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-regular fa-folder-open',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2025-02-10 15:42:49',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Personas',
                'url' => '/admin/people',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-person',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 1,
                'created_at' => '2025-04-07 09:43:00',
                'updated_at' => '2025-12-15 13:17:55',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Estructura Organizacional',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2025-12-15 13:13:43',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Empresas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-building',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 1,
                'created_at' => '2025-12-15 13:13:43',
                'updated_at' => '2025-12-15 13:13:43',
                'route' => 'admin.empresas.index',
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Sucursales',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-shop',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 2,
                'created_at' => '2025-12-15 13:13:43',
                'updated_at' => '2025-12-15 13:13:43',
                'route' => 'admin.sucursales.index',
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Departamentos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 3,
                'created_at' => '2025-12-15 13:13:43',
                'updated_at' => '2025-12-15 13:13:43',
                'route' => 'admin.departamentos.index',
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Gestión de Personal',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2025-12-15 13:13:43',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Empleados',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => NULL,
                'parent_id' => 23,
                'order' => 1,
                'created_at' => '2025-12-15 13:13:43',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'admin.empleados.index',
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Horarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-watch',
                'color' => NULL,
                'parent_id' => 23,
                'order' => 2,
                'created_at' => '2025-12-15 13:13:44',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'admin.horarios.index',
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Asignación de Horarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-forward',
                'color' => NULL,
                'parent_id' => 23,
                'order' => 3,
                'created_at' => '2025-12-15 13:13:44',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'admin.asignacion-horarios.index',
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Dispositivos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-wifi',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2025-12-15 13:13:44',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Dispositivos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-wifi',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 1,
                'created_at' => '2025-12-15 13:13:44',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'admin.dispositivos.index',
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Mapeo Empleados',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 2,
                'created_at' => '2025-12-15 13:13:44',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'admin.dispositivo-empleado.index',
                'parameters' => '',
            ),
            28 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Operaciones',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-activity',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2025-12-15 13:13:44',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => NULL,
                'parameters' => '',
            ),
            29 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Registros de Asistencia',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 30,
                'order' => 1,
                'created_at' => '2025-12-15 13:13:44',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'admin.registros-asistencia.index',
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Tipos de Incidencia',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => NULL,
                'parent_id' => 30,
                'order' => 2,
                'created_at' => '2025-12-15 13:13:44',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'admin.tipos-incidencia.index',
                'parameters' => '',
            ),
            31 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Incidencias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-warning',
                'color' => NULL,
                'parent_id' => 30,
                'order' => 3,
                'created_at' => '2025-12-15 13:13:44',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'admin.incidencias.index',
                'parameters' => '',
            ),
            32 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'Reportes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bar-chart',
                'color' => NULL,
                'parent_id' => 30,
                'order' => 4,
                'created_at' => '2025-12-15 13:13:44',
                'updated_at' => '2025-12-15 13:17:03',
                'route' => 'admin.reportes-asistencia.index',
                'parameters' => '',
            ),
        ));
        
        
    }
}